apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: expenses-web-ui-git
spec:
  type: git
  params:
    - name: revision
      value: keycloak
    - name: url
      value: https://github.com/nmajorov/expenses-web-ui.git
