apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-expenses-web-ui
spec:
  resources:
    - name: expenses-web-ui-git
      type: git
    - name: ui-image
      type: image

  tasks:
  - name: test
    taskRef:
      name: test-nodejs-app
    params:
      - name: VERSION
        value: "10"
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
        - name: source
          resource: expenses-web-ui-git
  - name: build-ui
    taskRef:
      name: s2i-nodejs
      kind: ClusterTask
    runAfter:
      - test
    params:
        - name: VERSION
          value: "10"
        - name: TLSVERIFY
          value: "false"
    resources:
      inputs:
        - name: source
          resource: expenses-web-ui-git
      outputs:
      - name: image
        resource: ui-image

  - name: deploy-nodejs-app
    taskRef:
      name: deploy-nodejs-app
    runAfter:
      - build-ui
    resources:
      inputs:
        - name: source
          resource: expenses-web-ui-git

