version: "3.5"

services:
  expense_app_build:
    build: ../
    container_name: "expenses-gui"
    volumes:
      - ../build:/usr/src/app/dist

  expense_app_web:
    image: nginx
    ports:
      - 80:80
    container_name: "expenses-gui"
    restart: unless-stopped
    volumes:
      - ../build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  build:
